#!/bin/bash
#
# Send Daily Health Reports via Email
# 使用 Mail.app 发送每日健康报告
#

RECIPIENT="revolutionljk@gmail.com"
OUTPUT_DIR="/Users/jimmylu/.openclaw/workspace/shared/health-reports/upload"

# 计算日期
YESTERDAY=$(date -v-1d '+%Y-%m-%d')
DAY_BEFORE=$(date -v-2d '+%Y-%m-%d')

echo "准备发送健康报告邮件..."
echo "收件人: $RECIPIENT"
echo "昨日: $YESTERDAY"
echo "前天: $DAY_BEFORE"

# 定义文件路径
REPORT_ZH="${OUTPUT_DIR}/${YESTERDAY}-report-zh.pdf"
REPORT_EN="${OUTPUT_DIR}/${YESTERDAY}-report-en.pdf"
COMP_ZH="${OUTPUT_DIR}/${DAY_BEFORE}-vs-${YESTERDAY}-comparison-zh.pdf"
COMP_EN="${OUTPUT_DIR}/${DAY_BEFORE}-vs-${YESTERDAY}-comparison-en.pdf"

# 检查文件是否存在
for file in "$REPORT_ZH" "$REPORT_EN" "$COMP_ZH" "$COMP_EN"; do
    if [ ! -f "$file" ]; then
        echo "❌ 文件不存在: $file"
        exit 1
    fi
done

echo "✅ 所有报告文件已找到"

# 发送邮件 1: 中文单日报告
osascript << EOF
tell application "Mail"
    set newMsg to make new outgoing message with properties {subject:"每日健康报告 - ${YESTERDAY}", content:"您好，

请查收 ${YESTERDAY} 的健康报告（中文版）。

报告包含：
- Recovery Score 恢复评分
- 心血管指标分析（HRV、静息心率）
- 运动数据统计（步数、活动能量、锻炼）
- 睡眠质量评估
- AI 个性化建议

数据来源：Apple Health + Google Fit
时区：UTC+8 (北京时间)

如有疑问，请随时联系。

--
由 Health Agent 自动生成"}
    tell newMsg
        make new to recipient at end of to recipients with properties {address:"${RECIPIENT}"}
        tell content
            make new attachment with properties {file name:"${REPORT_ZH}"}
        end tell
        send
    end tell
end tell
EOF

echo "✅ 邮件 1/4 已发送: 中文单日报告"
sleep 2

# 发送邮件 2: 英文单日报告
osascript << EOF
tell application "Mail"
    set newMsg to make new outgoing message with properties {subject:"Daily Health Report - ${YESTERDAY}", content:"Hello,

Please find attached your daily health report for ${YESTERDAY} (English version).

Report includes:
- Recovery Score
- Cardiovascular metrics (HRV, Resting Heart Rate)
- Activity data (Steps, Active Energy, Exercise)
- Sleep quality analysis
- AI personalized recommendations

Data sources: Apple Health + Google Fit
Timezone: UTC+8 (Beijing Time)

Best regards,
--
Generated by Health Agent"}
    tell newMsg
        make new to recipient at end of to recipients with properties {address:"${RECIPIENT}"}
        tell content
            make new attachment with properties {file name:"${REPORT_EN}"}
        end tell
        send
    end tell
end tell
EOF

echo "✅ 邮件 2/4 已发送: 英文单日报告"
sleep 2

# 发送邮件 3: 中文对比报告
osascript << EOF
tell application "Mail"
    set newMsg to make new outgoing message with properties {subject:"健康对比报告 - ${DAY_BEFORE} vs ${YESTERDAY}", content:"您好，

请查收 ${DAY_BEFORE} 与 ${YESTERDAY} 的健康对比分析报告（中文版）。

报告包含：
- 两日数据并排对比
- AI 模式识别与洞察
- 变化趋势分析
- 个性化建议

AI 会自动识别身体状态模式（如"过度透支-身体代偿"），并提供针对性建议。

--
由 Health Agent 自动生成"}
    tell newMsg
        make new to recipient at end of to recipients with properties {address:"${RECIPIENT}"}
        tell content
            make new attachment with properties {file name:"${COMP_ZH}"}
        end tell
        send
    end tell
end tell
EOF

echo "✅ 邮件 3/4 已发送: 中文对比报告"
sleep 2

# 发送邮件 4: 英文对比报告
osascript << EOF
tell application "Mail"
    set newMsg to make new outgoing message with properties {subject:"Health Comparison Report - ${DAY_BEFORE} vs ${YESTERDAY}", content:"Hello,

Please find attached the health comparison report for ${DAY_BEFORE} vs ${YESTERDAY} (English version).

Report includes:
- Side-by-side data comparison
- AI pattern recognition and insights
- Trend analysis
- Personalized recommendations

AI automatically identifies body state patterns (e.g., "overdraft-compensation mode") and provides targeted advice.

Best regards,
--
Generated by Health Agent"}
    tell newMsg
        make new to recipient at end to recipients with properties {address:"${RECIPIENT}"}
        tell content
            make new attachment with properties {file name:"${COMP_EN}"}
        end tell
        send
    end tell
end tell
EOF

echo "✅ 邮件 4/4 已发送: 英文对比报告"
echo ""
echo "🎉 所有健康报告邮件已发送成功！"
echo "收件人: ${RECIPIENT}"
echo "发送时间: $(date '+%Y-%m-%d %H:%M:%S')"
